spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none

app.global.ttl: 600

logging.level:
  root: info
  org:
    springframework.web: info
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
